sudo: false
language: c

cache:
  directories:
  - $HOME/.stack

matrix:
  include:
    - env: CABALVER=1.24 GHCVER=7.10.3 HAPPYVER=1.19.5 RESOLVER=lts-6.2
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.10.3
            - cabal-install-1.24
            - happy-1.19.5
    - env: CABALVER=1.24 GHCVER=8.0.1 HAPPYVER=1.19.5 RESOLVER=lts-7.3
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.1
            - cabal-install-1.24
            - happy-1.19.5
before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  # Export GHC paths
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:$PATH

script:
  - stack --no-terminal --skip-ghc-check build --resolver $RESOLVER
