#language: haskell
#ghc: "7.10"
sudo: false

cache:
  directories:
  - $HOME/.stack

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.3 HAPPYVER=1.19.5
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.10.3
            - cabal-install-1.22
            - happy-1.19.5

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  # Export GHC paths
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:$PATH

script:
  - stack --no-terminal --skip-ghc-check build
